### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by eliomaroun** [NoTests/RxFeedback.kt#4]
The dependency I added in build.gradle file is not working.
Can someone please send me the right dependency??

**Comment by JurajBegovac** [comment]
So you added this:
```
implementation 'com.github.NoTests:RxFeedback.kt:x.y.z'
```
???

You can see the latest version at the top of the readme: `0.1.6`. So you need to add this:
```
implementation 'com.github.NoTests:RxFeedback.kt:0.1.6'
```
